// FETCH ALL NEWS ARTICLES
export const GET_ALL_NEWS = "GET_ALL_NEWS";
export const GET_ALL_NEWS_SUCCESS = "GET_ALL_NEWS_SUCCESS";
export const GET_ALL_NEWS_FAIL = "GET_ALL_NEWS_FAIL";

// SEARCH NEWS ARTICLES
export const SEARCH_NEWS_ARTICLES = "SEARCH_NEWS_ARTICLES";
export const SEARCH_NEWS_ARTICLES_SUCCESS = "SEARCH_NEWS_ARTICLES_SUCCESS";
export const SEARCH_NEWS_ARTICLES_FAIL = "SEARCH_NEWS_ARTICLES_FAIL";

// SIGNUP USERS
export const SIGN_UP_USER = "SIGN_UP_USER";
export const SIGN_UP_USER_SUCCESS = "SIGN_UP_USER_SUCCESS";
export const SIGN_UP_USER_FAIL = "SIGN_UP_USER_FAIL";

// LOGIN USERS
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

// SAVE NEWS
export const SAVE_NEWS = "SAVE_NEWS";
export const SAVE_NEWS_SUCCESS = "SAVE_NEWS_SUCCESS";
export const SAVE_NEWS_FAIL = "SAVE_NEWS_FAIL";

// retrieve news
export const GET_NEWS = "GET_NEWS";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_FAIL = "GET_NEWS_FAIL";
