// FETCH ALL NEWS ARTICLES
export const GET_ALL_NEWS = "GET_ALL_NEWS";
export const GET_ALL_NEWS_SUCCESS = "GET_ALL_NEWS_SUCCESS";
export const GET_ALL_NEWS_FAIL = "GET_ALL_NEWS_FAIL";

// SEARCH NEWS ARTICLES
export const SEARCH_NEWS_ARTICLES = "SEARCH_NEWS_ARTICLES";
export const SEARCH_NEWS_ARTICLES_SUCCESS = "SEARCH_NEWS_ARTICLES_SUCCESS";
export const SEARCH_NEWS_ARTICLES_FAIL = "SEARCH_NEWS_ARTICLES_FAIL";
